// Mock data for admin service (used when MONGO_URI=mock)
export const mockSettings = {
  maxFileSizeBytes: 10 * 1024 * 1024,
  allowedMimeTypes: ["image/jpeg", "image/png", "image/webp"],
  uploadDir: "uploads",
  corsOrigin: "http://localhost:5173",
  aiServiceUrl: "http://localhost:8000",
};

export const mockUploads = [
  {
    id: "mock-upload-1",
    fileId: "file-101",
    fileName: "passport_photo_john.png",
    sizeBytes: 2048500,
    preset: "US Passport",
    background: "Blue",
    status: "processed",
    userEmail: "john.doe@example.com",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    fileUrl: "/uploads/mock-passport-1.jpg",
  },
  {
    id: "mock-upload-2",
    fileId: "file-102",
    fileName: "id_card_mary.jpg",
    sizeBytes: 1548200,
    preset: "Schengen Visa",
    background: "White",
    status: "processing",
    userEmail: "mary.smith@example.com",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    fileUrl: null,
  },
  {
    id: "mock-upload-3",
    fileId: "file-103",
    fileName: "selfie_raw.webp",
    sizeBytes: 4500000,
    preset: "Custom Passport",
    background: "Grey",
    status: "uploaded",
    userEmail: "alex.jones@example.com",
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    fileUrl: null,
  },
  {
    id: "mock-upload-4",
    fileId: "file-104",
    fileName: "damaged_input.png",
    sizeBytes: 890000,
    preset: "UK Passport",
    background: "White",
    status: "failed",
    userEmail: "hacker@example.com",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    fileUrl: null,
  },
];

export const mockUsers = [
  {
    id: "mock-user-1",
    fullName: "Mock Administrator",
    email: "admin@snappass.ai",
    role: "admin",
    isActive: true,
    lastLoginAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 100000000).toISOString(),
  },
  {
    id: "mock-user-2",
    fullName: "John Doe",
    email: "john.doe@example.com",
    role: "user",
    isActive: true,
    lastLoginAt: new Date(Date.now() - 3600000).toISOString(),
    createdAt: new Date(Date.now() - 50000000).toISOString(),
  },
  {
    id: "mock-user-3",
    fullName: "Mary Smith",
    email: "mary.smith@example.com",
    role: "user",
    isActive: true,
    lastLoginAt: new Date(Date.now() - 7200000).toISOString(),
    createdAt: new Date(Date.now() - 40000000).toISOString(),
  },
];
