import { Router } from 'express';
import { sanitizeInput } from '../middleware/sanitize.middleware.js';
import { requestAuditMiddleware } from '../middleware/auditLogger.middleware.js';
import { deepRequestSanitizer } from '../middleware/requestSanitizer.middleware.js';
import authRoutes from './auth.routes.js';
import uploadRoutes from './upload.routes.js';
import imageRoutes from './image.routes.js';
import processRoutes from './process.routes.js';
import printRoutes from './print.routes.js';
import healthRoutes from './health.routes.js';
import complianceRoutes from './compliance.routes.js';
import testimonialRoutes from './testimonial.routes.js';
import uploadHistoryRoutes from './uploadHistory.routes.js';
import auditRoutes from './audit.routes.js';
import presetsRoutes from './presets.routes.js';
import docsRoutes from './docs.routes.js';
import analyticsRoutes from './analytics.routes.js';
import batchRoutes from './batch.routes.js';
import cleanupRoutes from './cleanup.routes.js';

const router = Router();

router.use(sanitizeInput);
router.use(requestAuditMiddleware);
router.use(deepRequestSanitizer);
router.use('/auth', authRoutes);
router.use('/upload', uploadRoutes);
router.use('/process', imageRoutes);
router.use('/process', processRoutes);
router.use('/print', printRoutes);
router.use('/compliance', complianceRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/upload-history', uploadHistoryRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/presets', presetsRoutes);
router.use('/docs', docsRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/batch', batchRoutes);
router.use('/cleanup', cleanupRoutes);

export { healthRoutes };
export default router;
